//
//  File.swift
//  
//
//  Created by Matt Bonney on 7/14/22.
//

import SwiftUI

public extension LabeledColor {
    static let watchOS_yellowGold = LabeledColor("yellow gold", hex: "#edda98")
    static let watchOS_gold = LabeledColor("gold", hex: "#cead7a")
    static let watchOS_roseGold = LabeledColor("rose gold", hex: "#f2c1a2")
    static let watchOS_white = LabeledColor("white", hex: "#ffffff")
    static let watchOS_gray = LabeledColor("gray", hex: "#8e8d93")
    static let watchOS_red = LabeledColor("red", hex: "#df0b24")
    static let watchOS_orange = LabeledColor("orange", hex: "#fe5131")
    static let watchOS_nectarine = LabeledColor("nectarine", hex: "#fc694f")
    static let watchOS_apricot = LabeledColor("apricot", hex: "#fc7351")
    static let watchOS_peach = LabeledColor("peach", hex: "#e57e5e")
    static let watchOS_papaya = LabeledColor("papaya", hex: "#ff8542")
    static let watchOS_lightOrange = LabeledColor("light orange", hex: "#ff9602")
    static let watchOS_mellowYellow = LabeledColor("mellow yellow", hex: "#f6f3bd")
    static let watchOS_yellow = LabeledColor("yellow", hex: "#e9cb0d")
    static let watchOS_pollen = LabeledColor("pollen", hex: "#ffd25b")
    static let watchOS_canaryYellow = LabeledColor("canary yellow", hex: "#fedd44")
    static let watchOS_flashLight = LabeledColor("flash light", hex: "#f7ec00")
    static let watchOS_flash = LabeledColor("flash", hex: "#e1f323")
    static let watchOS_green = LabeledColor("green", hex: "#8ce229")
    static let watchOS_spearmint = LabeledColor("spearmint", hex: "#84e98c")
    static let watchOS_mint = LabeledColor("mint", hex: "#adec9d")
    static let watchOS_turquoise = LabeledColor("turquoise", hex: "#9ed5cb")
    static let watchOS_lightBlue = LabeledColor("light blue", hex: "#6ac4dc")
    static let watchOS_blue = LabeledColor("blue", hex: "#19b6fb")
    static let watchOS_royalBlue = LabeledColor("royal blue", hex: "#62aded")
    static let watchOS_cerulean = LabeledColor("cerulean", hex: "#95c4e8")
    static let watchOS_lilac = LabeledColor("lilac", hex: "#c1d8fc")
    static let watchOS_mistBlue = LabeledColor("mist blue", hex: "#b3b8a7")
    static let watchOS_azure = LabeledColor("azure", hex: "#879aa1")
    static let watchOS_stormGray = LabeledColor("storm gray", hex: "#689797")
    static let watchOS_pacificGreen = LabeledColor("pacific green", hex: "#127f9c")
    static let watchOS_blueCobalt = LabeledColor("blue cobalt", hex: "#477f9d")
    static let watchOS_darkTeal = LabeledColor("dark teal", hex: "#357293")
    static let watchOS_blueHorizon = LabeledColor("blue horizon", hex: "#26689d")
    static let watchOS_denimBlue = LabeledColor("denim blue", hex: "#5b83a8")
    static let watchOS_midnightBlue = LabeledColor("midnight blue", hex: "#6083be")
    static let watchOS_oceanBlue = LabeledColor("ocean blue", hex: "#7288c7")
    static let watchOS_delftBlue = LabeledColor("delft blue", hex: "#5677bf")
    static let watchOS_indigo = LabeledColor("indigo", hex: "#5864a2")
    static let watchOS_purple = LabeledColor("purple", hex: "#987cf7")
    static let watchOS_ultraViolet = LabeledColor("ultra violet", hex: "#7157be")
    static let watchOS_lavenderGray = LabeledColor("lavender gray", hex: "#8687a4")
    static let watchOS_lavender = LabeledColor("lavender", hex: "#b399a6")
    static let watchOS_pinkSand = LabeledColor("pink sand", hex: "#f4c1bd")
    static let watchOS_lightPink = LabeledColor("light pink", hex: "#f4b0aa")
    static let watchOS_vintageRose = LabeledColor("vintage rose", hex: "#f4aba5")
    static let watchOS_pink = LabeledColor("pink", hex: "#fe5964")
    static let watchOS_electricPink = LabeledColor("electric pink", hex: "#ff4e51")
    static let watchOS_dragonFruit = LabeledColor("dragon fruit", hex: "#f34a7e")
    static let watchOS_hibiscus = LabeledColor("hibiscus", hex: "#fa255b")
    static let watchOS_roseRed = LabeledColor("rose red", hex: "#b92946")
    static let watchOS_camellia = LabeledColor("camellia", hex: "#c94544")
    static let watchOS_flamingo = LabeledColor("flamingo", hex: "#d3836a")
    static let watchOS_walnut = LabeledColor("walnut", hex: "#b08662")
    static let watchOS_stone = LabeledColor("stone", hex: "#ae9980")
    static let watchOS_antiqueWhite = LabeledColor("antique white", hex: "#d4b694")
    static let watchOS_softWhite = LabeledColor("soft white", hex: "#ddd1bb")
    static let watchOS_pebble = LabeledColor("pebble", hex: "#ad9d8e")
    static let watchOS_cocoa = LabeledColor("cocoa", hex: "#9b8d8c")
    static let watchOS_darkOlive = LabeledColor("dark olive", hex: "#8c8c76")
    static let watchOS_voltNike = LabeledColor("volt", hex: "#dffd04")
    static let watchOS_celestialTealNike = LabeledColor("celestial teal", hex: "#4c7b7c")
    static let watchOS_smokyMauveNike = LabeledColor("smoky mauve", hex: "#ab7e6b")
    static let watchOS_oliveFlakNike = LabeledColor("olive flak", hex: "#7d713a")
    static let watchOS_cargoKhakiNike = LabeledColor("cargo khaki", hex: "#4e4e32")
    static let watchOS_obsidianIndigoNike = LabeledColor("obsidian indigo", hex: "#2d2b36")
    static let watchOS_anthraciteNike = LabeledColor("anthracite", hex: "#686969")
    static let watchOS_wolfGrayNike = LabeledColor("wolf gray", hex: "#a6a5aa")
    static let watchOS_lightSilverNike = LabeledColor("light silver", hex: "#c4c5c0")
    static let watchOS_particleBeigeNike = LabeledColor("particle beige", hex: "#c4b1a4")
    static let watchOS_lightBoneNike = LabeledColor("light bone", hex: "#c9bc9a")
    static let watchOS_terraBlushNike = LabeledColor("terra blush", hex: "#a67762")
    static let watchOS_totalOrangeNike = LabeledColor("total orange", hex: "#ee664d")
    static let watchOS_brightCrimsonNike = LabeledColor("bright crimson", hex: "#ff3838")
    static let watchOS_barelyRoseNike = LabeledColor("barely rose", hex: "#f9cebd")
    static let watchOS_lightVioletNike = LabeledColor("light violet", hex: "#ffcfba")
    static let watchOS_violetDustNike = LabeledColor("violet dust", hex: "#ad757f")
    static let watchOS_indigoNike = LabeledColor("indigo", hex: "#587ba1")
    static let watchOS_blueOrbitNike = LabeledColor("blue orbit", hex: "#0189a1")
    static let watchOS_auroraGreenNike = LabeledColor("aurora green", hex: "#92dbd8")
    static let watchOS_tealTintNike = LabeledColor("teal tint", hex: "#d7f5d0")
    static let watchOS_hyperGrapeNike = LabeledColor("hyper grape", hex: "#8549b3")
    static let watchOS_spruceFogNike = LabeledColor("spruce fog", hex: "#c6bd93")

    static var watchOSColors: [LabeledColor] {
        [.watchOS_yellowGold, .watchOS_gold, .watchOS_roseGold, .watchOS_white, .watchOS_gray, .watchOS_red, .watchOS_orange, .watchOS_nectarine, .watchOS_apricot, .watchOS_peach, .watchOS_papaya, .watchOS_lightOrange, .watchOS_mellowYellow, .watchOS_yellow, .watchOS_pollen, .watchOS_canaryYellow, .watchOS_flashLight, .watchOS_flash, .watchOS_green, .watchOS_spearmint, .watchOS_mint, .watchOS_turquoise, .watchOS_lightBlue, .watchOS_blue, .watchOS_royalBlue, .watchOS_cerulean, .watchOS_lilac, .watchOS_mistBlue, .watchOS_azure, .watchOS_stormGray, .watchOS_pacificGreen, .watchOS_blueCobalt, .watchOS_darkTeal, .watchOS_blueHorizon, .watchOS_denimBlue, .watchOS_midnightBlue, .watchOS_oceanBlue, .watchOS_delftBlue, .watchOS_indigo, .watchOS_purple, .watchOS_ultraViolet, .watchOS_lavenderGray, .watchOS_lavender, .watchOS_pinkSand, .watchOS_lightPink, .watchOS_vintageRose, .watchOS_pink, .watchOS_electricPink, .watchOS_dragonFruit, .watchOS_hibiscus, .watchOS_roseRed, .watchOS_camellia, .watchOS_flamingo, .watchOS_walnut, .watchOS_stone, .watchOS_antiqueWhite, .watchOS_softWhite, .watchOS_pebble, .watchOS_cocoa, .watchOS_darkOlive, .watchOS_voltNike, .watchOS_celestialTealNike, .watchOS_smokyMauveNike, .watchOS_oliveFlakNike, .watchOS_cargoKhakiNike, .watchOS_obsidianIndigoNike, .watchOS_anthraciteNike, .watchOS_wolfGrayNike, .watchOS_lightSilverNike, .watchOS_particleBeigeNike, .watchOS_lightBoneNike, .watchOS_terraBlushNike, .watchOS_totalOrangeNike, .watchOS_brightCrimsonNike, .watchOS_barelyRoseNike, .watchOS_lightVioletNike, .watchOS_violetDustNike, .watchOS_indigoNike, .watchOS_blueOrbitNike, .watchOS_auroraGreenNike, .watchOS_tealTintNike, .watchOS_hyperGrapeNike, .watchOS_spruceFogNike]
    }
}
