//
//  File.swift
//  
//
//  Created by Matt Bonney on 7/14/22.
//

import SwiftUI

public extension Color {
    enum watchOS {
        public static let yellowGold =         Color(hex: "#edda98")
        public static let gold =           Color(hex: "#cead7a")
        public static let roseGold =       Color(hex: "#f2c1a2")
        public static let white =      Color(hex: "#ffffff")
        public static let gray =       Color(hex: "#8e8d93")
        public static let red =        Color(hex: "#df0b24")
        public static let orange =         Color(hex: "#fe5131")
        public static let nectarine =      Color(hex: "#fc694f")
        public static let apricot =        Color(hex: "#fc7351")
        public static let peach =      Color(hex: "#e57e5e")
        public static let papaya =         Color(hex: "#ff8542")
        public static let lightOrange =        Color(hex: "#ff9602")
        public static let mellowYellow =       Color(hex: "#f6f3bd")
        public static let yellow =         Color(hex: "#e9cb0d")
        public static let pollen =         Color(hex: "#ffd25b")
        public static let canaryYellow =       Color(hex: "#fedd44")
        public static let flashLight =         Color(hex: "#f7ec00")
        public static let flash =      Color(hex: "#e1f323")
        public static let green =      Color(hex: "#8ce229")
        public static let spearmint =      Color(hex: "#84e98c")
        public static let mint =       Color(hex: "#adec9d")
        public static let turquoise =      Color(hex: "#9ed5cb")
        public static let lightBlue =      Color(hex: "#6ac4dc")
        public static let blue =       Color(hex: "#19b6fb")
        public static let royalBlue =      Color(hex: "#62aded")
        public static let cerulean =       Color(hex: "#95c4e8")
        public static let lilac =      Color(hex: "#c1d8fc")
        public static let mistBlue =       Color(hex: "#b3b8a7")
        public static let azure =      Color(hex: "#879aa1")
        public static let stormGray =      Color(hex: "#689797")
        public static let pacificGreen =       Color(hex: "#127f9c")
        public static let blueCobalt =         Color(hex: "#477f9d")
        public static let darkTeal =       Color(hex: "#357293")
        public static let blueHorizon =        Color(hex: "#26689d")
        public static let denimBlue =      Color(hex: "#5b83a8")
        public static let midnightBlue =       Color(hex: "#6083be")
        public static let oceanBlue =      Color(hex: "#7288c7")
        public static let delftBlue =      Color(hex: "#5677bf")
        public static let indigo =         	Color(hex: "#5864a2")
        public static let purple =             Color(hex: "#987cf7")
        public static let ultraViolet =        Color(hex: "#7157be")
        public static let lavenderGray =       Color(hex: "#8687a4")
        public static let lavender =           Color(hex: "#b399a6")
        public static let pinkSand =           Color(hex: "#f4c1bd")
        public static let lightPink =          Color(hex: "#f4b0aa")
        public static let vintageRose =        Color(hex: "#f4aba5")
        public static let pink =               Color(hex: "#fe5964")
        public static let electricPink =       Color(hex: "#ff4e51")
        public static let dragonFruit =        Color(hex: "#f34a7e")
        public static let hibiscus =           Color(hex: "#fa255b")
        public static let roseRed =            Color(hex: "#b92946")
        public static let camellia =           Color(hex: "#c94544")
        public static let flamingo =           Color(hex: "#d3836a")
        public static let walnut =             Color(hex: "#b08662")
        public static let stone =              Color(hex: "#ae9980")
        public static let antiqueWhite =       Color(hex: "#d4b694")
        public static let softWhite =          Color(hex: "#ddd1bb")
        public static let pebble =             Color(hex: "#ad9d8e")
        public static let cocoa =              Color(hex: "#9b8d8c")
        public static let darkOlive =          Color(hex: "#8c8c76")

        public enum nike {
            public static let volt =               Color(hex: "#dffd04")
            public static let celestialTeal =      Color(hex: "#4c7b7c")
            public static let smokyMauve =         Color(hex: "#ab7e6b")
            public static let oliveFlak =          Color(hex: "#7d713a")
            public static let cargoKhaki =         Color(hex: "#4e4e32")
            public static let obsidianIndigo =     Color(hex: "#2d2b36")
            public static let anthracite =         Color(hex: "#686969")
            public static let wolfGray =           Color(hex: "#a6a5aa")
            public static let lightSilver =        Color(hex: "#c4c5c0")
            public static let particleBeige =      Color(hex: "#c4b1a4")
            public static let lightBone =          Color(hex: "#c9bc9a")
            public static let terraBlush =         Color(hex: "#a67762")
            public static let totalOrange =        Color(hex: "#ee664d")
            public static let brightCrimson =      Color(hex: "#ff3838")
            public static let barelyRose =         Color(hex: "#f9cebd")
            public static let lightViolet =        Color(hex: "#ffcfba")
            public static let violetDust =         Color(hex: "#ad757f")
            public static let indigo =             Color(hex: "#587ba1")
            public static let blueOrbit =          Color(hex: "#0189a1")
            public static let auroraGreen =        Color(hex: "#92dbd8")
            public static let tealTint =           Color(hex: "#d7f5d0")
            public static let hyperGrape =         Color(hex: "#8549b3")
            public static let spruceFog =          Color(hex: "#c6bd93")
        }
    }
}

public extension LabeledColor {
    public static let watchOS_yellowGold = LabeledColor("yellow gold", hex: "#edda98")
    public static let watchOS_gold = LabeledColor("gold", hex: "#cead7a")
    public static let watchOS_roseGold = LabeledColor("rose gold", hex: "#f2c1a2")
    public static let watchOS_white = LabeledColor("white", hex: "#ffffff")
    public static let watchOS_gray = LabeledColor("gray", hex: "#8e8d93")
    public static let watchOS_red = LabeledColor("red", hex: "#df0b24")
    public static let watchOS_orange = LabeledColor("orange", hex: "#fe5131")
    public static let watchOS_nectarine = LabeledColor("nectarine", hex: "#fc694f")
    public static let watchOS_apricot = LabeledColor("apricot", hex: "#fc7351")
    public static let watchOS_peach = LabeledColor("peach", hex: "#e57e5e")
    public static let watchOS_papaya = LabeledColor("papaya", hex: "#ff8542")
    public static let watchOS_lightOrange = LabeledColor("light orange", hex: "#ff9602")
    public static let watchOS_mellowYellow = LabeledColor("mellow yellow", hex: "#f6f3bd")
    public static let watchOS_yellow = LabeledColor("yellow", hex: "#e9cb0d")
    public static let watchOS_pollen = LabeledColor("pollen", hex: "#ffd25b")
    public static let watchOS_canaryYellow = LabeledColor("canary yellow", hex: "#fedd44")
    public static let watchOS_flashLight = LabeledColor("flash light", hex: "#f7ec00")
    public static let watchOS_flash = LabeledColor("flash", hex: "#e1f323")
    public static let watchOS_green = LabeledColor("green", hex: "#8ce229")
    public static let watchOS_spearmint = LabeledColor("spearmint", hex: "#84e98c")
    public static let watchOS_mint = LabeledColor("mint", hex: "#adec9d")
    public static let watchOS_turquoise = LabeledColor("turquoise", hex: "#9ed5cb")
    public static let watchOS_lightBlue = LabeledColor("light blue", hex: "#6ac4dc")
    public static let watchOS_blue = LabeledColor("blue", hex: "#19b6fb")
    public static let watchOS_royalBlue = LabeledColor("royal blue", hex: "#62aded")
    public static let watchOS_cerulean = LabeledColor("cerulean", hex: "#95c4e8")
    public static let watchOS_lilac = LabeledColor("lilac", hex: "#c1d8fc")
    public static let watchOS_mistBlue = LabeledColor("mist blue", hex: "#b3b8a7")
    public static let watchOS_azure = LabeledColor("azure", hex: "#879aa1")
    public static let watchOS_stormGray = LabeledColor("storm gray", hex: "#689797")
    public static let watchOS_pacificGreen = LabeledColor("pacific green", hex: "#127f9c")
    public static let watchOS_blueCobalt = LabeledColor("blue cobalt", hex: "#477f9d")
    public static let watchOS_darkTeal = LabeledColor("dark teal", hex: "#357293")
    public static let watchOS_blueHorizon = LabeledColor("blue horizon", hex: "#26689d")
    public static let watchOS_denimBlue = LabeledColor("denim blue", hex: "#5b83a8")
    public static let watchOS_midnightBlue = LabeledColor("midnight blue", hex: "#6083be")
    public static let watchOS_oceanBlue = LabeledColor("ocean blue", hex: "#7288c7")
    public static let watchOS_delftBlue = LabeledColor("delft blue", hex: "#5677bf")
    public static let watchOS_indigo = LabeledColor("indigo", hex: "#5864a2")
    public static let watchOS_purple = LabeledColor("purple", hex: "#987cf7")
    public static let watchOS_ultraViolet = LabeledColor("ultra violet", hex: "#7157be")
    public static let watchOS_lavenderGray = LabeledColor("lavender gray", hex: "#8687a4")
    public static let watchOS_lavender = LabeledColor("lavender", hex: "#b399a6")
    public static let watchOS_pinkSand = LabeledColor("pink sand", hex: "#f4c1bd")
    public static let watchOS_lightPink = LabeledColor("light pink", hex: "#f4b0aa")
    public static let watchOS_vintageRose = LabeledColor("vintage rose", hex: "#f4aba5")
    public static let watchOS_pink = LabeledColor("pink", hex: "#fe5964")
    public static let watchOS_electricPink = LabeledColor("electric pink", hex: "#ff4e51")
    public static let watchOS_dragonFruit = LabeledColor("dragon fruit", hex: "#f34a7e")
    public static let watchOS_hibiscus = LabeledColor("hibiscus", hex: "#fa255b")
    public static let watchOS_roseRed = LabeledColor("rose red", hex: "#b92946")
    public static let watchOS_camellia = LabeledColor("camellia", hex: "#c94544")
    public static let watchOS_flamingo = LabeledColor("flamingo", hex: "#d3836a")
    public static let watchOS_walnut = LabeledColor("walnut", hex: "#b08662")
    public static let watchOS_stone = LabeledColor("stone", hex: "#ae9980")
    public static let watchOS_antiqueWhite = LabeledColor("antique white", hex: "#d4b694")
    public static let watchOS_softWhite = LabeledColor("soft white", hex: "#ddd1bb")
    public static let watchOS_pebble = LabeledColor("pebble", hex: "#ad9d8e")
    public static let watchOS_cocoa = LabeledColor("cocoa", hex: "#9b8d8c")
    public static let watchOS_darkOlive = LabeledColor("dark olive", hex: "#8c8c76")
    public static let watchOS_voltNike = LabeledColor("volt", hex: "#dffd04")
    public static let watchOS_celestialTealNike = LabeledColor("celestial teal", hex: "#4c7b7c")
    public static let watchOS_smokyMauveNike = LabeledColor("smoky mauve", hex: "#ab7e6b")
    public static let watchOS_oliveFlakNike = LabeledColor("olive flak", hex: "#7d713a")
    public static let watchOS_cargoKhakiNike = LabeledColor("cargo khaki", hex: "#4e4e32")
    public static let watchOS_obsidianIndigoNike = LabeledColor("obsidian indigo", hex: "#2d2b36")
    public static let watchOS_anthraciteNike = LabeledColor("anthracite", hex: "#686969")
    public static let watchOS_wolfGrayNike = LabeledColor("wolf gray", hex: "#a6a5aa")
    public static let watchOS_lightSilverNike = LabeledColor("light silver", hex: "#c4c5c0")
    public static let watchOS_particleBeigeNike = LabeledColor("particle beige", hex: "#c4b1a4")
    public static let watchOS_lightBoneNike = LabeledColor("light bone", hex: "#c9bc9a")
    public static let watchOS_terraBlushNike = LabeledColor("terra blush", hex: "#a67762")
    public static let watchOS_totalOrangeNike = LabeledColor("total orange", hex: "#ee664d")
    public static let watchOS_brightCrimsonNike = LabeledColor("bright crimson", hex: "#ff3838")
    public static let watchOS_barelyRoseNike = LabeledColor("barely rose", hex: "#f9cebd")
    public static let watchOS_lightVioletNike = LabeledColor("light violet", hex: "#ffcfba")
    public static let watchOS_violetDustNike = LabeledColor("violet dust", hex: "#ad757f")
    public static let watchOS_indigoNike = LabeledColor("indigo", hex: "#587ba1")
    public static let watchOS_blueOrbitNike = LabeledColor("blue orbit", hex: "#0189a1")
    public static let watchOS_auroraGreenNike = LabeledColor("aurora green", hex: "#92dbd8")
    public static let watchOS_tealTintNike = LabeledColor("teal tint", hex: "#d7f5d0")
    public static let watchOS_hyperGrapeNike = LabeledColor("hyper grape", hex: "#8549b3")
    public static let watchOS_spruceFogNike = LabeledColor("spruce fog", hex: "#c6bd93")

    static var watchOSColors: [LabeledColor] {
        [.watchOS_yellowGold, .watchOS_gold, .watchOS_roseGold, .watchOS_white, .watchOS_gray, .watchOS_red, .watchOS_orange, .watchOS_nectarine, .watchOS_apricot, .watchOS_peach, .watchOS_papaya, .watchOS_lightOrange, .watchOS_mellowYellow, .watchOS_yellow, .watchOS_pollen, .watchOS_canaryYellow, .watchOS_flashLight, .watchOS_flash, .watchOS_green, .watchOS_spearmint, .watchOS_mint, .watchOS_turquoise, .watchOS_lightBlue, .watchOS_blue, .watchOS_royalBlue, .watchOS_cerulean, .watchOS_lilac, .watchOS_mistBlue, .watchOS_azure, .watchOS_stormGray, .watchOS_pacificGreen, .watchOS_blueCobalt, .watchOS_darkTeal, .watchOS_blueHorizon, .watchOS_denimBlue, .watchOS_midnightBlue, .watchOS_oceanBlue, .watchOS_delftBlue, .watchOS_indigo, .watchOS_purple, .watchOS_ultraViolet, .watchOS_lavenderGray, .watchOS_lavender, .watchOS_pinkSand, .watchOS_lightPink, .watchOS_vintageRose, .watchOS_pink, .watchOS_electricPink, .watchOS_dragonFruit, .watchOS_hibiscus, .watchOS_roseRed, .watchOS_camellia, .watchOS_flamingo, .watchOS_walnut, .watchOS_stone, .watchOS_antiqueWhite, .watchOS_softWhite, .watchOS_pebble, .watchOS_cocoa, .watchOS_darkOlive, .watchOS_voltNike, .watchOS_celestialTealNike, .watchOS_smokyMauveNike, .watchOS_oliveFlakNike, .watchOS_cargoKhakiNike, .watchOS_obsidianIndigoNike, .watchOS_anthraciteNike, .watchOS_wolfGrayNike, .watchOS_lightSilverNike, .watchOS_particleBeigeNike, .watchOS_lightBoneNike, .watchOS_terraBlushNike, .watchOS_totalOrangeNike, .watchOS_brightCrimsonNike, .watchOS_barelyRoseNike, .watchOS_lightVioletNike, .watchOS_violetDustNike, .watchOS_indigoNike, .watchOS_blueOrbitNike, .watchOS_auroraGreenNike, .watchOS_tealTintNike, .watchOS_hyperGrapeNike, .watchOS_spruceFogNike]
    }
}
